mongodb:
  image: mongo:2.6
  restart: always
  command: mongod --smallfiles
  volumes:
    - ./db:/data/db
  expose:
    - "27017"

broker:
  build: .
  restart: always
  links:
    - mongodb
  ports:
    - "3100:3000"
