log4r_config:
  # define all loggers ...
  loggers:
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile_development
    - name      : test
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile_test
    - name      : production
      level     : WARN
      trace     : 'false'
      outputters :
      - datefile_production
    - name      : remote
      level     : INFO
      trace     : 'false'
  # define all outputters (incl. formatters)
  outputters:
    - type: DateFileOutputter
        name: datefile_production
        dirname: "log"
        filename: "production.log"
        formatter:
          date_pattern: '%H:%M:%S'
          pattern     : '%d %l: %m '
          type        : PatternFormatter
    - type: DateFileOutputter
      name: datefile_development
      dirname: "log"
      filename: "development.log"
      formatter:
        date_pattern: '%H:%M:%S'
        pattern     : '%d %l: %m '
        type        : PatternFormatter
    - type: DateFileOutputter
      name: datefile_test
      dirname: "log"
      filename: "test.log"
      formatter:
        date_pattern: '%H:%M:%S'
        pattern     : '%d %l: %m '
        type        : PatternFormatter