development:
  sessions:
    default:
      database: broker
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: broker
      hosts:
        - localhost:27017
      options:
        write:
          w: 1


production:
  sessions:
    default:
      database: broker
      hosts:
        - localhost:27017